# Generated by Django 4.0.5 on 2022-06-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gioBatDau', models.TimeField()),
                ('gioKetThuc', models.TimeField()),
                ('ca', models.CharField(max_length=2)),
                ('ghiChu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Front_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(max_length=255)),
                ('slider', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GiaoVien',
            fields=[
                ('maGV', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenGV', models.CharField(max_length=50)),
                ('gioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=50)),
                ('ngaySinh', models.DateField()),
                ('sdt', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50, null=True)),
                ('luongNgay', models.IntegerField()),
                ('duPhong2', models.CharField(blank=True, max_length=50, null=True)),
                ('duPhong3', models.CharField(blank=True, max_length=50, null=True)),
                ('duPhong4', models.CharField(blank=True, max_length=50, null=True)),
                ('quyen', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HocVien',
            fields=[
                ('maHV', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ngaySinh', models.DateField(blank=True, null=True)),
                ('gioiTinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('diaChi', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=50)),
                ('ghiChu', models.TextField(blank=True, null=True)),
                ('duPhong2', models.CharField(blank=True, max_length=50, null=True)),
                ('duPhong3', models.CharField(blank=True, max_length=50, null=True)),
                ('duPhong4', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhoaHoc',
            fields=[
                ('maKH', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenKH', models.CharField(max_length=50)),
                ('moTa', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ghiChu', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='KhoanKhac',
            fields=[
                ('maKK', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('soTienChi', models.IntegerField()),
                ('ngay', models.DateField()),
                ('noiDungChi', models.CharField(max_length=255)),
                ('soTienThu', models.IntegerField()),
                ('noiDungThu', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LopHoc',
            fields=[
                ('maLop', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenLop', models.CharField(max_length=50)),
                ('hocPhi_ca', models.IntegerField()),
                ('luongGV_ca', models.IntegerField()),
                ('hocPhi_dot', models.IntegerField()),
                ('luong_dot', models.IntegerField()),
                ('traTheoKhoa', models.BooleanField(default=False)),
                ('ngayBatDau', models.DateField(blank=True, null=True)),
                ('ngayKetThuc', models.DateField(blank=True, null=True)),
                ('soLuongHocVien', models.IntegerField(null=True)),
                ('soLuongHocVienMax', models.IntegerField(null=True)),
                ('duPhong1', models.CharField(blank=True, max_length=50, null=True)),
                ('duPhong2', models.CharField(blank=True, max_length=50, null=True)),
                ('caHoc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cahoc')),
                ('giaoVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.giaovien')),
            ],
        ),
        migrations.CreateModel(
            name='PhuHuynh',
            fields=[
                ('maPH', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenPH', models.CharField(max_length=50)),
                ('gioiTinh', models.CharField(choices=[('nam', 'Nam'), ('nu', 'Nữ'), ('khac', 'Khác')], default='khac', max_length=50)),
                ('ngaySinh', models.DateField(blank=True, null=True)),
                ('sdt1', models.CharField(max_length=50)),
                ('sdt2', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('soZalo', models.CharField(max_length=50)),
                ('duPhong2', models.CharField(blank=True, max_length=50)),
                ('duPhong3', models.CharField(blank=True, max_length=50)),
                ('duPhong4', models.CharField(blank=True, max_length=50)),
                ('hocVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hocvien')),
            ],
        ),
        migrations.CreateModel(
            name='Ngay_Lop_Hoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.CharField(choices=[('thu2', 'Thứ 2'), ('thu3', 'Thứ 3'), ('thu4', 'Thứ 4'), ('thu5', 'Thứ 5'), ('thu6', 'Thứ 6'), ('thu7', 'Thứ 7'), ('chunh', 'Chủ nhật')], default='chunh', max_length=255)),
                ('lopHoc_id', models.ManyToManyField(to='home.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='LuongGV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('soTienNhan', models.IntegerField()),
                ('ghiChu', models.TextField(blank=True)),
                ('giaoVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.giaovien')),
            ],
        ),
        migrations.CreateModel(
            name='HocVien_LopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hocPhiGiam', models.IntegerField(blank=True, default=0, null=True)),
                ('ghiChu', models.TextField(blank=True, null=True)),
                ('hocVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hocvien')),
                ('lopHoc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='HOCVIEN_buoihoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemDanhHV', models.BooleanField()),
                ('ngay', models.DateField()),
                ('dongTien', models.BooleanField(default=False)),
                ('ghiChu', models.TextField(blank=True)),
                ('hocVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hocvien')),
                ('lopHoc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.lophoc')),
            ],
        ),
        migrations.CreateModel(
            name='HocPhi_HocVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.DateField()),
                ('soTienDong', models.IntegerField()),
                ('soChuaThanhToan', models.IntegerField(null=True)),
                ('ghiChu', models.TextField(blank=True)),
                ('hocVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.hocvien')),
                ('phuHuynh_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.phuhuynh')),
            ],
        ),
        migrations.CreateModel(
            name='GIAOVIEN_buoihoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diemDanhGV', models.BooleanField()),
                ('ngay', models.DateField()),
                ('traLuong', models.CharField(max_length=50)),
                ('ghiChu', models.TextField(blank=True)),
                ('caHoc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.cahoc')),
                ('giaoVien_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.giaovien')),
                ('lopHoc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.lophoc')),
            ],
        ),
    ]
