# Generated by Django 4.0.5 on 2022-06-09 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NgayHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay', models.CharField(choices=[('thu2', 'Thứ 2'), ('thu3', 'Thứ 3'), ('thu4', 'Thứ 4'), ('thu5', 'Thứ 5'), ('thu6', 'Thứ 6'), ('thu7', 'Thứ 7'), ('chunh', 'Chủ nhật')], default='chunh', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ngay_lop_hoc',
            name='ngay',
            field=models.CharField(blank=True, choices=[('thu2', 'Thứ 2'), ('thu3', 'Thứ 3'), ('thu4', 'Thứ 4'), ('thu5', 'Thứ 5'), ('thu6', 'Thứ 6'), ('thu7', 'Thứ 7'), ('chunh', 'Chủ nhật')], default='chunh', max_length=255),
        ),
        migrations.CreateModel(
            name='NgayLopHoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lopHoc_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.lophoc')),
                ('ngayHoc', models.ManyToManyField(to='home.ngayhoc')),
            ],
        ),
    ]
