# Generated by Django 4.0.5 on 2022-06-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ngayhoc_alter_ngay_lop_hoc_ngay_ngaylophoc'),
    ]

    operations = [
        migrations.AddField(
            model_name='lophoc',
            name='ngayHoc',
            field=models.ManyToManyField(blank=True, null=True, to='home.ngayhoc'),
        ),
    ]
