# Generated by Django 4.0.5 on 2022-06-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_lophoc_ngayhoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngayhoc',
            name='ngay',
            field=models.CharField(choices=[('Thứ 2', 'Thứ 2'), ('Thứ 3', 'Thứ 3'), ('Thứ4', 'Thứ 4'), ('Thứ 5', 'Thứ 5'), ('Thứ 6', 'Thứ 6'), ('Thứ 7', 'Thứ 7'), ('Chử Nhật', 'Chử Nhật')], default='Chủ Nhật', max_length=255),
        ),
    ]
