# Generated by Django 4.0.5 on 2022-06-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_ngay_lop_hoc_ngay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ngaylophoc',
            name='lopHoc_id',
        ),
        migrations.RemoveField(
            model_name='ngaylophoc',
            name='ngayHoc',
        ),
        migrations.AddField(
            model_name='ngayhoc',
            name='lopHoc',
            field=models.ManyToManyField(to='home.lophoc'),
        ),
        migrations.AlterField(
            model_name='ngayhoc',
            name='ngay',
            field=models.CharField(choices=[('Thứ 2', 'Thứ 2'), ('Thứ 3', 'Thứ 3'), ('Thứ4', 'Thứ 4'), ('Thứ 5', 'Thứ 5'), ('Thứ 6', 'Thứ 6'), ('Thứ 7', 'Thứ 7'), ('Chủ Nhật', 'Chủ Nhật')], default='Chủ Nhật', max_length=255),
        ),
        migrations.DeleteModel(
            name='Ngay_Lop_Hoc',
        ),
        migrations.DeleteModel(
            name='NgayLopHoc',
        ),
    ]
