# Generated by Django 4.0.5 on 2022-06-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_lophoc_ngayhoc_remove_ngayhoc_lophoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='luong_dot',
            field=models.IntegerField(default=0),
        ),
    ]
