# Generated by Django 4.0.5 on 2022-06-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_lophoc_cahoc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hocphi_hocvien',
            name='soTienDong',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hocvien_buoihoc',
            name='ngay',
            field=models.DateField(blank=True, null=True),
        ),
    ]
