# Generated by Django 4.0.5 on 2022-06-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_hocphi_hocvien_sotiendong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lophoc',
            name='soLuongHocVien',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
